# Generated by Django 6.1 on 2026-08-13 21:04
#
# What a project that swapped ``ORGANIZATION_MEMBERSHIP_MODEL`` gets when
# ``is_active`` moves onto the abstract base: the column it already declared for
# itself becomes the base's, so the only change is to the field's ``help_text``.
# A project that had *no* such column gets a plain ``AddField`` here instead.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('customorgs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationmembership',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='organizationmembership',
            name='is_active',
            field=models.BooleanField(
                default=True,
                help_text=(
                    'Unset this instead of deleting the row. An inactive membership grants nothing: it '
                    'resolves no permissions and cannot be selected as the request organization.'
                ),
            ),
        ),
    ]
