# Generated by Django 6.1 on 2026-08-10 22:10

import django.db.models.deletion
import vinta_orgs.fields
import vinta_orgs.mixins
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [

        migrations.swappable_dependency(settings.ORGANIZATION_MODEL),
        ("articles", "0001_initial"),
        ("vinta_orgs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleStatistics",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("views", models.IntegerField(default=0)),
                (
                    "article",
                    vinta_orgs.fields.OrganizationSafeOneToOneObject(
                        editable=False,
                        from_fields=["article_fk", "organization"],
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistics",
                        to="articles.article",
                        to_fields=[None, "organization"],
                        unique=True,
                    ),
                ),
                (
                    "article_fk",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistics_fk_rel",
                        to="articles.article",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        default=vinta_orgs.mixins.get_default_organization,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.ORGANIZATION_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "article",
                    models.ForeignObject(
                        editable=False,
                        from_fields=["article_fk", "organization"],
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="articles.article",
                        to_fields=[None, "organization"],
                    ),
                ),
                (
                    "article_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments_fk_rel",
                        to="articles.article",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        default=vinta_orgs.mixins.get_default_organization,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.ORGANIZATION_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
                "default_manager_name": "objects",
            },
        ),
    ]
