# Generated by Django 6.1 on 2026-08-11 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_articlestatistics_comment"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="organization",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.organization",
            ),
        ),
        migrations.AlterField(
            model_name="articlestatistics",
            name="organization",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.organization",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="organization",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.organization",
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["organization", "id"], name="articles_ar_organiz_6338d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="articlestatistics",
            index=models.Index(
                fields=["organization", "id"], name="articles_ar_organiz_3809ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["organization", "id"], name="articles_co_organiz_9d031f_idx"
            ),
        ),
    ]
