# Generated by Django 6.1 on 2026-08-11 18:01

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_alter_article_organization_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "base_manager_name": "original_manager",
                "default_manager_name": "objects",
            },
        ),
        migrations.AlterModelOptions(
            name="articlestatistics",
            options={
                "base_manager_name": "original_manager",
                "default_manager_name": "objects",
            },
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={
                "base_manager_name": "original_manager",
                "default_manager_name": "objects",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={
                "base_manager_name": "original_manager",
                "default_manager_name": "objects",
            },
        ),
        migrations.AlterModelManagers(
            name="article",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("original_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="articlestatistics",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("original_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="comment",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("original_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="tag",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("original_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
