# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 23:37
#
# ``Organization`` and ``OrganizationMembership`` carry a ``swappable`` option
# and the relations point at ``settings.ORGANIZATION_MODEL`` rather than at
# ``organizations.Organization``. Both were edited into this historical
# migration rather than added by a later one, because ``swappable`` lives in
# ``CreateModel``'s options and ``AlterModelOptions`` cannot set it -- the same
# reason Django's own ``auth`` 0001 carries it.
#
# For a project on the default models this changes nothing about the schema:
# ``ORGANIZATION_MODEL`` defaults to ``organizations.Organization``, so the
# foreign keys resolve to the same table they always did.
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


sites_dep_migration = ('sites', '0002_alter_domain_unique',)


organization_fields = [
    ('id', models.AutoField(
        auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    ('created', model_utils.fields.AutoCreatedField(
        default=django.utils.timezone.now, editable=False, verbose_name='created')),
    ('modified', model_utils.fields.AutoLastModifiedField(
        default=django.utils.timezone.now, editable=False, verbose_name='modified')),
    ('name', models.CharField(max_length=255)),
    ('slug', models.CharField(max_length=255, unique=True)),
]


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        # Needed because ``OrganizationSite`` points at the configured
        # organization, which on a project that swapped it lives in another app.
        # On the default it resolves to ``('organizations', '__first__')``, a
        # same-app reference the migration loader ignores rather than treating
        # as a cycle.
        migrations.swappable_dependency(settings.ORGANIZATION_MODEL),
        sites_dep_migration,
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=organization_fields,
            options={
                'abstract': False,
                'swappable': 'ORGANIZATION_MODEL',
            },
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('groups', models.ManyToManyField(blank=True,
                                                  related_name='user_organization_groups', to='auth.Group')),
                ('permissions', models.ManyToManyField(blank=True,
                                                       related_name='user_organization_permissions', to='auth.Permission')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                             related_name='memberships', to=settings.ORGANIZATION_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                           related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'swappable': 'ORGANIZATION_MEMBERSHIP_MODEL',
            },
        ),
        migrations.CreateModel(
            name='OrganizationSite',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                              related_name='organization_site', to='sites.Site')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                             related_name='organization_sites', to=settings.ORGANIZATION_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='organizationmembership',
            unique_together=set([('user', 'organization')]),
        ),
    ]
