# Generated by Django 6.1 on 2026-08-11 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [

        migrations.swappable_dependency(settings.ORGANIZATION_MODEL),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("organizations", "0001_initial"),
        ("sites", "0002_alter_domain_unique"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationmembership",
            name="organization",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to=settings.ORGANIZATION_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="organizationsite",
            name="organization",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organization_sites",
                to=settings.ORGANIZATION_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="organizationmembership",
            index=models.Index(
                fields=["organization", "id"], name="organizatio_organiz_5ad970_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationsite",
            index=models.Index(
                fields=["organization", "id"], name="organizatio_organiz_3a20c3_idx"
            ),
        ),
    ]
