# Generated by Django 6.1 on 2026-08-11 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_alter_organizationmembership_organization_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="slug",
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
