# Generated by Django 6.1 on 2026-08-11 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_alter_organization_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="slug",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
