# Generated by Django 6.1 on 2026-08-11 18:01
#
# Records manager and Meta changes that already happened in code. Both
# ``AlterModelOptions`` and ``AlterModelManagers`` are state-only -- they touch
# no table -- so this is here purely to stop ``makemigrations --check`` reporting
# pending changes, in this repository and in projects installing it.
#
# What moved: ``base_manager_name`` on the scoping mixins went from ``objects``
# to ``original_manager``, and ``AbstractOrganizationMembership`` gained
# ``default_manager_name = 'objects'``. Django records the classes backing
# ``_base_manager`` and ``_default_manager`` in migration state, so changing
# which manager fills either role is a change it wants written down.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0004_alter_organization_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organizationmembership",
            options={"default_manager_name": "objects"},
        ),
    ]
