# Generated by Django 6.1 on 2026-08-12 13:26
#
# ``Organization`` and ``OrganizationMembership`` carry a ``swappable`` option
# and the relations point at ``settings.ORGANIZATION_MODEL`` rather than at
# ``vinta_orgs.Organization``, the same way Django's own ``auth`` 0001 does for
# ``AUTH_USER_MODEL``: ``swappable`` lives in ``CreateModel``'s options, and
# ``AlterModelOptions`` cannot set it, so it has to be here rather than in a
# later migration.
#
# For a project on the default models this changes nothing about the schema:
# ``ORGANIZATION_MODEL`` defaults to ``vinta_orgs.Organization``, so the foreign
# keys resolve to this app's own table.

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("sites", "0002_alter_domain_unique"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        # Added by hand: ``OrganizationSite`` and ``OrganizationMembership``
        # point at the configured organization, which on a project that swapped
        # it lives in another app. The autodetector leaves this out because on
        # the default it resolves to ``('vinta_orgs', '__first__')`` -- a
        # same-app reference the migration loader ignores rather than treating
        # as a cycle -- so it costs nothing there and is required elsewhere.
        migrations.swappable_dependency(settings.ORGANIZATION_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "abstract": False,
                "swappable": "ORGANIZATION_MODEL",
            },
        ),
        migrations.CreateModel(
            name="OrganizationMembership",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="user_organization_groups",
                        to="auth.group",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.ORGANIZATION_MODEL,
                    ),
                ),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="user_organization_permissions",
                        to="auth.permission",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "swappable": "ORGANIZATION_MEMBERSHIP_MODEL",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["organization", "id"],
                        name="vinta_orgs__organiz_f7b00b_idx",
                    )
                ],
                "unique_together": {("user", "organization")},
            },
        ),
        migrations.CreateModel(
            name="OrganizationSite",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_sites",
                        to=settings.ORGANIZATION_MODEL,
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_site",
                        to="sites.site",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["organization", "id"],
                        name="vinta_orgs__organiz_8976ef_idx",
                    )
                ],
            },
        ),
    ]
