# Generated by Django 6.1 on 2026-08-13 21:04
#
# ``is_active`` moved onto ``AbstractOrganizationMembership`` so the permission
# backend can gate on it; see the field's comment in ``vinta_orgs/models.py``.
#
# A project that swapped ``ORGANIZATION_MEMBERSHIP_MODEL`` gets this operation as
# a no-op -- ``AddField.database_forwards`` asks ``Options.can_migrate()``, which
# is False for a swapped-out model -- and picks the column up in its own app's
# migration instead, generated from the abstract base the same way.
#
# ``default=True`` with ``null=False`` is the cheap direction on every supported
# backend: PostgreSQL 11+ stores a non-volatile default in the catalog rather
# than rewriting the table, so this does not lock a large membership table for
# the length of a rewrite. Existing rows keep granting what they granted.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vinta_orgs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmembership',
            name='is_active',
            field=models.BooleanField(
                default=True,
                help_text=(
                    'Unset this instead of deleting the row. An inactive membership grants nothing: it '
                    'resolves no permissions and cannot be selected as the request organization.'
                ),
            ),
        ),
    ]
