# Generated by Django 6.1 on 2026-08-12 13:26

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.ORGANIZATION_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationSpecificFieldsValidator",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module_path", models.CharField(max_length=255)),
                (
                    "organizations",
                    models.ManyToManyField(
                        related_name="validators_available",
                        to=settings.ORGANIZATION_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "original_manager",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("original_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="OrganizationSpecificFieldDefinition",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "data_type",
                    model_utils.fields.StatusField(
                        choices=[
                            ("char", "char"),
                            ("text", "text"),
                            ("integer", "integer"),
                            ("float", "float"),
                            ("datetime", "datetime"),
                            ("date", "date"),
                        ],
                        default="char",
                        max_length=100,
                        no_check_for_status=True,
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                ("default_value", models.TextField()),
                ("table_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.ORGANIZATION_MODEL,
                    ),
                ),
                (
                    "table_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "validators",
                    models.ManyToManyField(
                        blank=True,
                        to="vinta_orgs_custom_data.organizationspecificfieldsvalidator",
                    ),
                ),
            ],
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("original_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="OrganizationSpecificFieldTextPivot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_id", models.PositiveIntegerField()),
                ("value", models.TextField()),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vinta_orgs_custom_data.organizationspecificfielddefinition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.ORGANIZATION_MODEL,
                    ),
                ),
                (
                    "row_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "original_manager",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("original_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="OrganizationSpecificTable",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.ORGANIZATION_MODEL,
                    ),
                ),
            ],
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("original_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="OrganizationSpecificTableRow",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.ORGANIZATION_MODEL,
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="vinta_orgs_custom_data.organizationspecifictable",
                    ),
                ),
            ],
            options={
                "base_manager_name": "original_manager",
                "default_manager_name": "original_manager",
            },
            managers=[
                ("original_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="OrganizationSpecificTablesPermission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("codename", models.CharField(max_length=100)),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.ORGANIZATION_MODEL,
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vinta_orgs_custom_data.organizationspecifictable",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "original_manager",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("original_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="OrganizationSpecificTablesGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_specific_tables_groups",
                        to="auth.group",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.ORGANIZATION_MODEL,
                    ),
                ),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="groups",
                        to="vinta_orgs_custom_data.organizationspecifictablespermission",
                    ),
                ),
            ],
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("original_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="OrganizationSpecificTablesRelationship",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        related_name="relationships",
                        to="vinta_orgs_custom_data.organizationspecifictablesgroup",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.ORGANIZATION_MODEL,
                    ),
                ),
                (
                    "permissions",
                    models.ManyToManyField(
                        related_name="relationships",
                        to="vinta_orgs_custom_data.organizationspecifictablespermission",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "original_manager",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("original_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="OrganizationSpecificFieldDateTimePivot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_id", models.PositiveIntegerField()),
                ("value", models.DateTimeField()),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.ORGANIZATION_MODEL,
                    ),
                ),
                (
                    "row_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vinta_orgs_custom_data.organizationspecificfielddefinition",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "original_manager",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["organization", "id"],
                        name="vinta_orgs__organiz_cff130_idx",
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("original_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="OrganizationSpecificFieldDatePivot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_id", models.PositiveIntegerField()),
                ("value", models.DateField()),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.ORGANIZATION_MODEL,
                    ),
                ),
                (
                    "row_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vinta_orgs_custom_data.organizationspecificfielddefinition",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "original_manager",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["organization", "id"],
                        name="vinta_orgs__organiz_22bc1d_idx",
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("original_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="OrganizationSpecificFieldCharPivot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_id", models.PositiveIntegerField()),
                ("value", models.CharField(max_length=255)),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.ORGANIZATION_MODEL,
                    ),
                ),
                (
                    "row_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vinta_orgs_custom_data.organizationspecificfielddefinition",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "original_manager",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["organization", "id"],
                        name="vinta_orgs__organiz_7ec022_idx",
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("original_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="OrganizationSpecificFieldFloatPivot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_id", models.PositiveIntegerField()),
                ("value", models.FloatField()),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vinta_orgs_custom_data.organizationspecificfielddefinition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.ORGANIZATION_MODEL,
                    ),
                ),
                (
                    "row_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "original_manager",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["organization", "id"],
                        name="vinta_orgs__organiz_dfdb4d_idx",
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("original_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="OrganizationSpecificFieldIntegerPivot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_id", models.PositiveIntegerField()),
                ("value", models.IntegerField()),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vinta_orgs_custom_data.organizationspecificfielddefinition",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.ORGANIZATION_MODEL,
                    ),
                ),
                (
                    "row_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "original_manager",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["organization", "id"],
                        name="vinta_orgs__organiz_20ed49_idx",
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("original_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name="organizationspecificfielddefinition",
            index=models.Index(
                fields=["organization", "id"], name="vinta_orgs__organiz_82d90b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="organizationspecificfielddefinition",
            unique_together={
                ("organization", "table_id", "table_content_type", "name")
            },
        ),
        migrations.AddIndex(
            model_name="organizationspecificfieldtextpivot",
            index=models.Index(
                fields=["organization", "id"], name="vinta_orgs__organiz_e2009a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationspecifictable",
            index=models.Index(
                fields=["organization", "id"], name="vinta_orgs__organiz_bba90f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="organizationspecifictable",
            unique_together={("organization", "name")},
        ),
        migrations.AddIndex(
            model_name="organizationspecifictablerow",
            index=models.Index(
                fields=["organization", "id"], name="vinta_orgs__organiz_18ce11_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationspecifictablespermission",
            index=models.Index(
                fields=["organization", "id"], name="vinta_orgs__organiz_6d4734_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationspecifictablesgroup",
            index=models.Index(
                fields=["organization", "id"], name="vinta_orgs__organiz_053b42_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="organizationspecifictablesgroup",
            unique_together={("group", "organization")},
        ),
        migrations.AddIndex(
            model_name="organizationspecifictablesrelationship",
            index=models.Index(
                fields=["organization", "id"], name="vinta_orgs__organiz_e77bd3_idx"
            ),
        ),
    ]
