# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 05:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import model_utils.fields
import organizations.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [

        migrations.swappable_dependency(settings.ORGANIZATION_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('organizations', '0001_initial'),
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationSpecificFieldCharPivot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_id', models.PositiveIntegerField()),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='OrganizationSpecificFieldDatePivot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_id', models.PositiveIntegerField()),
                ('value', models.DateField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='OrganizationSpecificFieldDateTimePivot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_id', models.PositiveIntegerField()),
                ('value', models.DateTimeField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='OrganizationSpecificFieldDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('data_type', model_utils.fields.StatusField(choices=[('char', 'char'), ('text', 'text'), ('integer', 'integer'), (
                    'float', 'float'), ('datetime', 'datetime'), ('date', 'date')], default='char', max_length=100, no_check_for_status=True)),
                ('is_required', models.BooleanField(default=False)),
                ('default_value', models.TextField()),
                ('table_id', models.PositiveIntegerField(blank=True, null=True)),
                ('table_content_type', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('organization', models.ForeignKey(default=organizations.mixins.get_default_organization,
                 on_delete=django.db.models.deletion.CASCADE, to=settings.ORGANIZATION_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationSpecificFieldFloatPivot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_id', models.PositiveIntegerField()),
                ('value', models.FloatField()),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 to='organizations_custom_data.OrganizationSpecificFieldDefinition')),
                ('row_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('organization', models.ForeignKey(default=organizations.mixins.get_default_organization,
                 on_delete=django.db.models.deletion.CASCADE, to=settings.ORGANIZATION_MODEL)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='OrganizationSpecificFieldIntegerPivot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_id', models.PositiveIntegerField()),
                ('value', models.IntegerField()),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 to='organizations_custom_data.OrganizationSpecificFieldDefinition')),
                ('row_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('organization', models.ForeignKey(default=organizations.mixins.get_default_organization,
                 on_delete=django.db.models.deletion.CASCADE, to=settings.ORGANIZATION_MODEL)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='OrganizationSpecificFieldsValidator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_path', models.CharField(max_length=255)),
                ('organizations', models.ManyToManyField(
                    related_name='validators_available', to=settings.ORGANIZATION_MODEL)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='OrganizationSpecificFieldTextPivot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_id', models.PositiveIntegerField()),
                ('value', models.TextField()),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 to='organizations_custom_data.OrganizationSpecificFieldDefinition')),
                ('row_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('organization', models.ForeignKey(default=organizations.mixins.get_default_organization,
                 on_delete=django.db.models.deletion.CASCADE, to=settings.ORGANIZATION_MODEL)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='OrganizationSpecificTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('organization', models.ForeignKey(default=organizations.mixins.get_default_organization,
                 on_delete=django.db.models.deletion.CASCADE, to=settings.ORGANIZATION_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationSpecificTableRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows',
                 to='organizations_custom_data.OrganizationSpecificTable')),
                ('organization', models.ForeignKey(default=organizations.mixins.get_default_organization,
                 on_delete=django.db.models.deletion.CASCADE, to=settings.ORGANIZATION_MODEL)),
            ],
            options={
                'base_manager_name': 'original_manager',
                'default_manager_name': 'original_manager',
            },
            managers=[
                ('original_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationSpecificTablesGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='organization_specific_tables_groups', to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationSpecificTablesPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 to='organizations_custom_data.OrganizationSpecificTable')),
                ('organization', models.ForeignKey(default=organizations.mixins.get_default_organization,
                 on_delete=django.db.models.deletion.CASCADE, to=settings.ORGANIZATION_MODEL)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='OrganizationSpecificTablesRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groups', models.ManyToManyField(related_name='relationships',
                 to='organizations_custom_data.OrganizationSpecificTablesGroup')),
                ('permissions', models.ManyToManyField(related_name='relationships',
                 to='organizations_custom_data.OrganizationSpecificTablesPermission')),
                ('organization', models.ForeignKey(default=organizations.mixins.get_default_organization,
                 on_delete=django.db.models.deletion.CASCADE, to=settings.ORGANIZATION_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
            },
        ),
        migrations.AddField(
            model_name='organizationspecifictablesgroup',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='groups',
                                         to='organizations_custom_data.OrganizationSpecificTablesPermission'),
        ),
        migrations.AddField(
            model_name='organizationspecifictablesgroup',
            name='organization',
            field=models.ForeignKey(default=organizations.mixins.get_default_organization,
                                    on_delete=django.db.models.deletion.CASCADE, to=settings.ORGANIZATION_MODEL),
        ),
        migrations.AddField(
            model_name='organizationspecificfielddefinition',
            name='validators',
            field=models.ManyToManyField(
                blank=True, to='organizations_custom_data.OrganizationSpecificFieldsValidator'),
        ),
        migrations.AddField(
            model_name='organizationspecificfielddatetimepivot',
            name='definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='organizations_custom_data.OrganizationSpecificFieldDefinition'),
        ),
        migrations.AddField(
            model_name='organizationspecificfielddatetimepivot',
            name='row_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='organizationspecificfielddatetimepivot',
            name='organization',
            field=models.ForeignKey(default=organizations.mixins.get_default_organization,
                                    on_delete=django.db.models.deletion.CASCADE, to=settings.ORGANIZATION_MODEL),
        ),
        migrations.AddField(
            model_name='organizationspecificfielddatepivot',
            name='definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='organizations_custom_data.OrganizationSpecificFieldDefinition'),
        ),
        migrations.AddField(
            model_name='organizationspecificfielddatepivot',
            name='row_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='organizationspecificfielddatepivot',
            name='organization',
            field=models.ForeignKey(default=organizations.mixins.get_default_organization,
                                    on_delete=django.db.models.deletion.CASCADE, to=settings.ORGANIZATION_MODEL),
        ),
        migrations.AddField(
            model_name='organizationspecificfieldcharpivot',
            name='definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='organizations_custom_data.OrganizationSpecificFieldDefinition'),
        ),
        migrations.AddField(
            model_name='organizationspecificfieldcharpivot',
            name='row_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='organizationspecificfieldcharpivot',
            name='organization',
            field=models.ForeignKey(default=organizations.mixins.get_default_organization,
                                    on_delete=django.db.models.deletion.CASCADE, to=settings.ORGANIZATION_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='organizationspecifictablesgroup',
            unique_together=set([('group', 'organization')]),
        ),
        migrations.AlterUniqueTogether(
            name='organizationspecifictable',
            unique_together=set([('organization', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='organizationspecificfielddefinition',
            unique_together=set([('organization', 'table_id', 'table_content_type', 'name')]),
        ),
    ]
