# Generated by Django 6.1 on 2026-08-11 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("organizations", "0002_alter_organizationmembership_organization_and_more"),
        ("organizations_custom_data", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationspecificfieldcharpivot",
            name="organization",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.organization",
            ),
        ),
        migrations.AlterField(
            model_name="organizationspecificfielddatepivot",
            name="organization",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.organization",
            ),
        ),
        migrations.AlterField(
            model_name="organizationspecificfielddatetimepivot",
            name="organization",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.organization",
            ),
        ),
        migrations.AlterField(
            model_name="organizationspecificfielddefinition",
            name="organization",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.organization",
            ),
        ),
        migrations.AlterField(
            model_name="organizationspecificfieldfloatpivot",
            name="organization",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.organization",
            ),
        ),
        migrations.AlterField(
            model_name="organizationspecificfieldintegerpivot",
            name="organization",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.organization",
            ),
        ),
        migrations.AlterField(
            model_name="organizationspecificfieldtextpivot",
            name="organization",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.organization",
            ),
        ),
        migrations.AlterField(
            model_name="organizationspecifictable",
            name="organization",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.organization",
            ),
        ),
        migrations.AlterField(
            model_name="organizationspecifictablerow",
            name="organization",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.organization",
            ),
        ),
        migrations.AlterField(
            model_name="organizationspecifictablesgroup",
            name="organization",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.organization",
            ),
        ),
        migrations.AlterField(
            model_name="organizationspecifictablespermission",
            name="organization",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.organization",
            ),
        ),
        migrations.AlterField(
            model_name="organizationspecifictablesrelationship",
            name="organization",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.organization",
            ),
        ),
        migrations.AddIndex(
            model_name="organizationspecificfieldcharpivot",
            index=models.Index(
                fields=["organization", "id"], name="organizatio_organiz_746477_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationspecificfielddatepivot",
            index=models.Index(
                fields=["organization", "id"], name="organizatio_organiz_3ef9c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationspecificfielddatetimepivot",
            index=models.Index(
                fields=["organization", "id"], name="organizatio_organiz_097b41_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationspecificfielddefinition",
            index=models.Index(
                fields=["organization", "id"], name="organizatio_organiz_f12839_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationspecificfieldfloatpivot",
            index=models.Index(
                fields=["organization", "id"], name="organizatio_organiz_6c2192_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationspecificfieldintegerpivot",
            index=models.Index(
                fields=["organization", "id"], name="organizatio_organiz_11c92e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationspecificfieldtextpivot",
            index=models.Index(
                fields=["organization", "id"], name="organizatio_organiz_7b231f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationspecifictable",
            index=models.Index(
                fields=["organization", "id"], name="organizatio_organiz_585158_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationspecifictablerow",
            index=models.Index(
                fields=["organization", "id"], name="organizatio_organiz_25c3cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationspecifictablesgroup",
            index=models.Index(
                fields=["organization", "id"], name="organizatio_organiz_9d5dab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationspecifictablespermission",
            index=models.Index(
                fields=["organization", "id"], name="organizatio_organiz_ab9e6d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationspecifictablesrelationship",
            index=models.Index(
                fields=["organization", "id"], name="organizatio_organiz_857bdb_idx"
            ),
        ),
    ]
