# Generated by Django 6.1 on 2026-08-11 18:01
#
# Records manager and Meta changes that already happened in code. Both
# ``AlterModelOptions`` and ``AlterModelManagers`` are state-only -- they touch
# no table -- so this is here purely to stop ``makemigrations --check`` reporting
# pending changes, in this repository and in projects installing it.
#
# What moved: ``base_manager_name`` on the scoping mixins went from ``objects``
# to ``original_manager``, and ``AbstractOrganizationMembership`` gained
# ``default_manager_name = 'objects'``. Django records the classes backing
# ``_base_manager`` and ``_default_manager`` in migration state, so changing
# which manager fills either role is a change it wants written down.

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "organizations_custom_data",
            "0002_alter_organizationspecificfieldcharpivot_organization_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organizationspecificfieldcharpivot",
            options={
                "base_manager_name": "original_manager",
                "default_manager_name": "objects",
            },
        ),
        migrations.AlterModelOptions(
            name="organizationspecificfielddatepivot",
            options={
                "base_manager_name": "original_manager",
                "default_manager_name": "objects",
            },
        ),
        migrations.AlterModelOptions(
            name="organizationspecificfielddatetimepivot",
            options={
                "base_manager_name": "original_manager",
                "default_manager_name": "objects",
            },
        ),
        migrations.AlterModelOptions(
            name="organizationspecificfieldfloatpivot",
            options={
                "base_manager_name": "original_manager",
                "default_manager_name": "objects",
            },
        ),
        migrations.AlterModelOptions(
            name="organizationspecificfieldintegerpivot",
            options={
                "base_manager_name": "original_manager",
                "default_manager_name": "objects",
            },
        ),
        migrations.AlterModelOptions(
            name="organizationspecificfieldsvalidator",
            options={
                "base_manager_name": "original_manager",
                "default_manager_name": "objects",
            },
        ),
        migrations.AlterModelOptions(
            name="organizationspecificfieldtextpivot",
            options={
                "base_manager_name": "original_manager",
                "default_manager_name": "objects",
            },
        ),
        migrations.AlterModelOptions(
            name="organizationspecifictablespermission",
            options={
                "base_manager_name": "original_manager",
                "default_manager_name": "objects",
            },
        ),
        migrations.AlterModelOptions(
            name="organizationspecifictablesrelationship",
            options={
                "base_manager_name": "original_manager",
                "default_manager_name": "objects",
            },
        ),
        migrations.AlterModelManagers(
            name="organizationspecificfieldcharpivot",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("original_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="organizationspecificfielddatepivot",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("original_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="organizationspecificfielddatetimepivot",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("original_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="organizationspecificfielddefinition",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("original_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="organizationspecificfieldfloatpivot",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("original_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="organizationspecificfieldintegerpivot",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("original_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="organizationspecificfieldsvalidator",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("original_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="organizationspecificfieldtextpivot",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("original_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="organizationspecifictable",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("original_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="organizationspecifictablesgroup",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("original_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="organizationspecifictablespermission",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("original_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="organizationspecifictablesrelationship",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("original_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
